// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWqc_uS6eqM23vW6qHyM_Lfm0F0o1sN1Y',
    appId: '1:299565543270:web:c2d9a4e837be4ea867a2a7',
    messagingSenderId: '299565543270',
    projectId: 'flutter-spotify-clone-4df3c',
    authDomain: 'flutter-spotify-clone-4df3c.firebaseapp.com',
    storageBucket: 'flutter-spotify-clone-4df3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa7EElMAWDPZ7FNE89I-h0fZ0FdlwD1kI',
    appId: '1:299565543270:android:717d44c8f6e3d75967a2a7',
    messagingSenderId: '299565543270',
    projectId: 'flutter-spotify-clone-4df3c',
    storageBucket: 'flutter-spotify-clone-4df3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChqVGGCnTDeXFdrIc5Gay1LHXCJ3fKmqY',
    appId: '1:299565543270:ios:732be1f5666dc21067a2a7',
    messagingSenderId: '299565543270',
    projectId: 'flutter-spotify-clone-4df3c',
    storageBucket: 'flutter-spotify-clone-4df3c.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
